#!/bin/bash

while true; do
    clear
    echo -n "Please enter IP-Address to remote control: "
    read UserIPAddress

    echo -n "Please enter a username which has enough permissions: "
    read UserName

    clear
    echo "Choose what you want to do:"
    echo "1. Restart"
    echo "2. Shutdown"
    echo "3. Custom"
    read -p "Choose [1-3]: " UserChoice

    case $UserChoice in
        1)
            ssh -t $UserName@$UserIPAddress "sudo shutdown now -r"
            ;;
        2)
            ssh -t $UserName@$UserIPAddress "sudo shutdown now"
            ;;
        3)
            echo -n "Please enter the command you want to use: "
            read UserCommand
            ssh -t $UserName@$UserIPAddress "$UserCommand"
            ;;
        *)
            echo "Invalid choice"
            ;;
    esac

    read -p "Press enter to continue..."
    clear

    read -p "Do you want to use another IP? (y/n): " UserAgain
    if [ "$UserAgain" == "y" ]; then
        continue
    else
	clear
        break
    fi
done
